#!/usr/bin/env python3
"""Finance concept -> animal behavior match workbook (2 rated matches each)."""

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

# Each row: (category, concept, aspect,
#            match1_name, match1_desc, match1_quality,
#            match2_name, match2_desc, match2_quality, notes)
V = "Web-verified"  # shorthand for the notes column

DATA = [
# ===================== MARKETS & MICROSTRUCTURE =====================
("Markets & Microstructure", "The inversion instant in a crash",
 "The exact moment the crowd's 'buy because others buy' signal flips to 'sell because others sell.'",
 "Fish-school flash expansion (escape wave)",
 "In a tight school, each fish copies the turns of its nearest neighbors. When one fish detects a predator and bolts, the startle ripples outward at a speed faster than the predator, and the entire school reverses direction in a fraction of a second. The same copy-your-neighbor rule that organized the calm school instantly organizes the panic.",
 88,
 "Wildebeest stampede trigger",
 "A grazing herd is relaxed until a single animal bolts. Because each wildebeest reacts to its neighbors' movement rather than verifying the threat itself, the herd flips from calm grazing to full flight in seconds. The trigger is one actor, but the inversion is collective and near-instant.",
 84, ""),

("Markets & Microstructure", "Information cascades",
 "The point where people stop using their own private information and simply copy the last actor's choice.",
 "Ant pheromone-trail following (and the death spiral)",
 "Ants lay and follow pheromone trails; each ant reinforces the path of those before it instead of independently evaluating routes. This can lock a colony onto a suboptimal trail, and in army ants can cause a 'death spiral' where a circular trail traps thousands following each other to exhaustion. Private information is abandoned in favor of the collective track.",
 88,
 "Mate-choice copying (guppies, sage grouse)",
 "Females observe which males other females chose and copy that choice, overriding their own assessment of the male. A male seen being chosen becomes more attractive purely because he was chosen, exactly like buying because others bought.",
 82, "Both well documented"),

("Markets & Microstructure", "Momentum as self-fuel",
 "Rising prices recruiting new buyers, where the crowd's growing size is itself the reason to join.",
 "Desert locust gregarious phase change",
 "Solitary locusts are shy loners, but crowding triggers a serotonin surge that physically transforms them into gregarious swarmers that actively seek other locusts. Density creates more density: the crowd itself is the cause of joining the crowd, a pure self-reinforcing feedback loop identical to price momentum.",
 92,
 "Mountain pine beetle mass attack",
 "Individual beetles cannot overcome a healthy tree's resin defenses, so they emit aggregation pheromones. Early success recruits more beetles, whose arrival recruits still more, until the rising swarm overwhelms the tree. Growing numbers are themselves the signal to pile in.",
 84, V),

("Markets & Microstructure", "Liquidity evaporation",
 "Everyone reaching for the same exit at once physically shrinking the exit.",
 "Wildebeet river-crossing crush",
 "At a migration river ford, thousands of wildebeest funnel through one narrow crossing. The crush at the bottleneck drowns and tramples animals not because the river is impassable but because everyone demands the same exit simultaneously. Capacity that existed in calm vanishes under synchronized demand.",
 85,
 "Bait-ball collapse under attack",
 "A dense fish bait ball is protective until predators strike from all sides; the very tightness that gave safety now prevents fast dispersal, and individuals cannot find room to flee. The crowd that provided depth suddenly offers no way out.",
 76, ""),

("Markets & Microstructure", "The short squeeze",
 "Trapped sellers being forced to buy back, pouring fuel on the very fire burning them.",
 "Constrictor snake's tightening coil",
 "A constrictor does not crush; it tightens a little each time the prey exhales, so every breath the prey takes to struggle is used to ratchet the coil tighter. Each attempt to act against the squeeze makes the squeeze worse, mirroring shorts whose every move to cover drives the price higher.",
 78,
 "Hagfish slime backfire",
 "When a predator bites a hagfish, the fish releases expanding slime that clogs the attacker's gills; the harder and more aggressively the predator attacks, the more it chokes on its own assault. Aggression aimed downward rebounds catastrophically on the aggressor.",
 70, "Both are 'force backfires' analogies, moderate fit"),

("Markets & Microstructure", "Mean reversion",
 "An over-stretched price snapping back toward its long-run baseline.",
 "Lynx-hare population cycles",
 "Hare numbers boom, lynx follow and overshoot, hares crash, lynx crash, and the cycle returns toward a long-run equilibrium. Every overshoot in either direction is pulled back by the coupled system, the textbook image of values oscillating around a baseline.",
 88,
 "Thermoregulatory set-point",
 "Endotherms continuously correct body temperature back to a fixed set point; any deviation up or down triggers compensating mechanisms (shivering, panting). Persistent pull back to a baseline is the core of homeostasis and of mean reversion.",
 80, ""),

("Markets & Microstructure", "The bid-ask spread",
 "A tiny toll charged for providing immediate availability to whoever wants in or out now.",
 "Cleaner-fish station",
 "Cleaner wrasse run 'stations' on the reef, removing parasites from any client that arrives, providing an immediate service in exchange for a small meal. The cleaner is a standing market-maker who is always there to transact, taking a tiny cut for providing immediacy.",
 80,
 "Ant-aphid honeydew toll",
 "Ants protect aphid colonies and in return continuously harvest a small toll of honeydew. The ant provides a reliable standing service and skims a modest, steady margin for it.",
 72, "Cleaner fish " + V),

("Markets & Microstructure", "Market-maker inventory risk",
 "Being stuck holding stock you must offload before its value drifts against you.",
 "Honeybee forager tremble dance",
 "Foragers return with nectar that must be handed to receiver bees for processing. When receivers are overwhelmed, foragers are left holding nectar they cannot offload and perform a 'tremble dance' to recruit more handlers. Holding un-offloaded inventory in a bottleneck is the exact problem a market-maker faces.",
 80,
 "Squirrel's perishable held cache",
 "A squirrel that has gathered food it has not yet buried or eaten holds a perishable, theft-prone asset; every hour held risks spoilage or pilfering before it can be 'offloaded' into storage.",
 74, ""),

("Markets & Microstructure", "Front-running",
 "Acting an instant ahead of a large known incoming order to skim the move.",
 "Frigatebird piracy (kleptoparasitism)",
 "Frigatebirds watch other seabirds returning with full crops and intercept them mid-flight, forcing them to drop the catch, which the frigatebird grabs first. It profits by reading another's incoming 'order' and acting a beat ahead of delivery.",
 80,
 "Cattle egret following grazers",
 "Egrets follow large grazers and grab insects flushed out a split second before the prey can escape. They position themselves to capture value the moment a larger mover creates it.",
 78, ""),

("Markets & Microstructure", "Slippage on large orders",
 "Your own buying pushing the price up against you as the order fills.",
 "Whale lunge-feeding scatters the krill",
 "A lunge-feeding whale engulfs a krill patch, but the act of feeding disperses the swarm, so each successive mouthful is sparser and costlier to obtain. The forager's own consumption degrades the very resource it is consuming.",
 78,
 "Elephants depleting a waterhole",
 "As a herd drinks and wallows, it muddies and lowers the waterhole, so each later drinker gets worse water. Large consumption visibly worsens the conditions for the remainder of the same demand.",
 72, ""),

("Markets & Microstructure", "Price discovery",
 "Thousands of tiny independent signals aggregating into one shared number.",
 "Honeybee swarm quorum (nest-site selection)",
 "Scout bees inspect candidate nest sites and advertise each with a waggle dance whose vigor scales with site quality (about 100 circuits for an excellent site, 12 for a poor one). The swarm aggregates these many independent assessments and commits when one site reaches a quorum, converting distributed private information into a single collective decision.",
 94,
 "Ant pheromone foraging allocation",
 "A colony allocates foragers across food sources roughly in proportion to each source's quality, because better sources earn stronger pheromone reinforcement. Distributed individual sampling aggregates into a colony-level 'price' for each patch.",
 84, "Bee quorum " + V),

("Markets & Microstructure", "Flight to quality",
 "Capital abruptly fleeing risky assets and crowding into the few safest ones during panic.",
 "Prey fleeing to refuge",
 "When a predator appears, foragers in the open abandon rich but exposed feeding grounds and crowd into the safest refuge (trees, burrows, cliffs), accepting lower returns for safety. Risk perception instantly reprices the open ground to near-worthless.",
 82,
 "Reef fish darting into coral",
 "Small reef fish foraging in open water dart en masse into coral crevices the instant a predator strikes, abandoning food for the safest available cover.",
 78, ""),

("Markets & Microstructure", "The greater-fool dynamic",
 "Buying something overpriced solely because you expect a more eager buyer behind you.",
 "Bowerbird trinket valuation",
 "Male bowerbirds collect and fiercely guard shiny, intrinsically worthless objects (bottle caps, berries, glass) that have value only because females and rivals treat them as valuable. Worth is purely conventional and sustained by others' regard, not by any intrinsic use.",
 75,
 "Hermit crab vacancy chain",
 "When a large new shell appears, hermit crabs queue by size and each swaps up, handing its old shell down the line. Each crab's gain depends entirely on someone behind it wanting the shell it vacates.",
 70, "Animals don't trade for resale; flagged as a conceptual stretch"),

("Markets & Microstructure", "Capitulation",
 "The final exhausted mass sell-off that empties out the last holders and marks the bottom.",
 "Absconding bee colony",
 "When conditions become hopeless (disease, starvation, repeated disturbance), an entire bee colony abandons the hive at once and leaves. The final mass exit empties the position completely, after which only the cleared comb remains.",
 80,
 "Tonic immobility (final surrender)",
 "A cornered prey animal, after exhausting all escape efforts, goes limp in tonic immobility, the behavioral equivalent of total give-up. It marks the end of resistance.",
 76, ""),

("Markets & Microstructure", "The dead-cat bounce",
 "A brief deceptive recovery inside a larger ongoing decline.",
 "Semelparous death-bloom",
 "Agave and some bamboos channel a lifetime of stored energy into one spectacular final flowering, then die. The dramatic burst looks like vigor but is actually the terminal event, not a recovery.",
 80,
 "Death-throe reflex twitch",
 "A mortally wounded animal often shows a last burst of reflexive movement that resembles renewed struggle but is merely a dying spasm, not genuine recovery.",
 72, ""),

# ===================== RISK & INSURANCE =====================
("Risk & Insurance", "Risk pooling",
 "Individual catastrophic loss absorbed by the collective surplus of the group.",
 "Vampire bat reciprocal blood sharing",
 "Vampire bats die after roughly 60 hours without a blood meal, and on any night some fail to feed. Bats that fed regurgitate blood to roost-mates that did not, and recipients reciprocate later; sharing tracks both kinship and the chance to be repaid. Individual bad luck is absorbed by the colony's collective surplus, the purest natural model of mutual insurance.",
 96,
 "African wild dog communal provisioning",
 "Pack members share kills and regurgitate meat to those that stayed behind, including the sick and the pups. Each individual's hunting luck is pooled so no single member starves on a bad day.",
 82, "Vampire bat " + V),

("Risk & Insurance", "Tail-risk preparation",
 "Stockpiling against the rare, high-cost event you almost never actually witness.",
 "Acorn woodpecker granary",
 "Acorn woodpeckers drill granary trees with up to 50,000 holes and stockpile far more acorns than an average winter requires, maintaining the store across generations. The surplus is insurance against the rare brutal season that would otherwise wipe out the group.",
 88,
 "Camel hump reserves",
 "A camel stores fat in its hump that can be metabolized for energy (and water) during long droughts it may face only occasionally. The reserve is sized for the rare extreme, not the average day.",
 80, "Acorn woodpecker " + V),

("Risk & Insurance", "Hedging",
 "Accepting a small certain cost now to cap a large uncertain loss later.",
 "Bet-hedging via staggered germination/diapause",
 "Desert annual seeds and insect eggs stay dormant and germinate or hatch across several different years rather than all at once. This lowers the average yield (the certain cost) but guarantees a bad year cannot wipe out the entire generation (capping the catastrophic loss).",
 90,
 "Multiple escape-burrow maintenance",
 "Ground squirrels expend steady effort maintaining several burrow entrances they mostly never need. The small ongoing cost caps the catastrophic loss of being caught with no exit during an attack.",
 78, "Bet-hedging is the classic biological term for hedging"),

("Risk & Insurance", "The diversification effect",
 "Spreading across uncorrelated bets to cut volatility without cutting expected return.",
 "Scatter-hoarding across many caches",
 "Eurasian jays and squirrels bury food in hundreds of separate, widely spaced caches rather than one larder. Because raids, rot, and discovery hit caches independently, no single failure destroys the store, lowering variance without lowering the expected harvest.",
 90,
 "Wide seed dispersal across microhabitats",
 "Plants disperse offspring across many varied sites so that local droughts, fires, or grazers cannot eliminate all of them. Spreading bets across uncorrelated locations smooths survival.",
 80, "Eurasian jay " + V),

("Risk & Insurance", "Correlation breakdown in a crisis",
 "Things that normally move independently suddenly all moving together at the worst moment.",
 "Selfish-herd convergence under attack",
 "Animals that forage independently across a field instantly all rush toward the group's center when a predator strikes, each shrinking its own 'domain of danger.' Independence that held in calm collapses into perfect correlation exactly when safety from diversification was most needed.",
 84,
 "Synchronized panic flush",
 "A flock whose members were feeding on their own schedules flushes as one at a single alarm; previously uncorrelated individual behavior snaps into lockstep under threat.",
 78, "Selfish herd " + V),

("Risk & Insurance", "Moral hazard",
 "Taking on more risk precisely because someone else will absorb the downside.",
 "Cuckoo offloading parental cost",
 "A cuckoo lays its egg in another bird's nest and leaves entirely, taking the reproductive gamble while the host bears every cost of incubation and feeding. The parasite takes the risk because another party absorbs the consequences.",
 86,
 "Sentinel-protected reckless foraging",
 "Foragers under the protection of a posted sentinel feed more boldly and in riskier spots than they would alone, because the cost of a missed predator is borne by the warning system rather than by their own vigilance.",
 78, ""),

("Risk & Insurance", "Adverse selection",
 "The riskiest participants being the most eager to join the pool.",
 "Brood parasites targeting poor-defense hosts",
 "Cuckoos preferentially parasitize host individuals and species least able to detect and reject foreign eggs. The 'pool' of accepted eggs fills disproportionately with the riskiest, least-discriminating partners.",
 78,
 "Worst-condition fish keenest at the cleaner station",
 "The most parasite-laden, poorest-condition clients have the strongest incentive to seek out cleaning, so a cleaner's queue skews toward the highest-maintenance, riskiest customers.",
 76, "Adverse selection has no perfect animal analog; moderate fit"),

("Risk & Insurance", "Reinsurance",
 "Insurers insuring each other so no single one can be wiped out by one event.",
 "Bottlenose dolphin nested alliances",
 "Male dolphins form first-order alliances to herd mates, and these are backed by second-order alliances of alliances that can be called on when a first-order group is overpowered. Risk is layered: pools are themselves backed by larger pools.",
 84,
 "Coalitions-of-coalitions in primates",
 "Smaller cooperative coalitions ally into larger meta-coalitions, so a group that loses a contest can draw on backing beyond its own membership, spreading risk one level up.",
 76, ""),

("Risk & Insurance", "Deductibles",
 "Making the insured share the small losses so they don't make frivolous claims.",
 "Penguin huddle edge-time",
 "Emperor penguins rotate through the freezing outer edge of the huddle before reaching the warm center; every member must absorb a stint of cold to access the pooled warmth. Each individual bears a small share of the loss as the price of coverage.",
 75,
 "Reciprocal grooming cost",
 "An animal must spend its own time and effort grooming a partner before it can expect grooming in return; the upfront personal cost screens out pure free-riders.",
 72, "Penguin huddle " + V + "; deductible link is conceptual"),

("Risk & Insurance", "Basis risk",
 "A hedge that almost-but-not-quite tracks the thing it was meant to protect.",
 "Snowshoe hare coat-color mismatch",
 "Hares molt to white on a day-length schedule as winter camouflage, but when snowfall arrives late or melts early, the white coat no longer matches the brown ground. The protective 'hedge' fails to track actual conditions, leaving exposed risk.",
 85,
 "Imperfect Batesian mimicry",
 "A harmless mimic resembling a toxic model gains protection only to the degree the resemblance holds; an imperfect match leaves a residual gap predators can exploit. The hedge tracks the protective reference incompletely.",
 80, ""),

("Risk & Insurance", "Survivorship bias",
 "Judging strategy by only the winners that survived, ignoring the silent dead.",
 "The visible salmon that made it upstream",
 "We see the salmon leaping the falls and reaching the spawning grounds, but not the thousands that died en route or never started. Judging the journey by the visible survivors badly overstates its odds.",
 80,
 "Only-the-fast-are-seen escape",
 "The gazelles and lions we observe are disproportionately the ones whose speed kept them in the game; the slow were removed and are invisible, skewing any inference about the typical individual.",
 74, "More an observational fallacy than a discrete behavior"),

("Risk & Insurance", "Ruin risk",
 "A loss so total that you can never get back to the table to play again.",
 "Semelparity (one-shot reproduction)",
 "Pacific salmon, mayflies, and many octopuses reproduce exactly once and then die; there is no second attempt. The single irreversible event embodies a loss/ commitment from which no recovery is possible.",
 82,
 "Starvation-edge foraging",
 "An animal whose reserves are nearly gone must forage, but a single fatal error ends everything; near the edge, behavior is dominated by avoiding the one mistake that cannot be survived.",
 80, ""),

("Risk & Insurance", "Kelly bet sizing",
 "Scaling each bet to your real edge so a streak of bad luck can't ruin you.",
 "Risk-sensitive foraging",
 "Animals adjust how much risk they take to their energy state: when reserves are comfortable they choose safe, steady food, but when near starvation they accept high-variance gambles because the safe option guarantees death. Bet size tracks the true state and edge, just as Kelly prescribes.",
 85,
 "Lack's clutch-size optimum",
 "Birds lay the clutch size that maximizes the number of young actually surviving to fledge, not the maximum eggs possible, because over-laying starves the whole brood. Sizing the bet for long-run growth, not the largest single wager.",
 80, ""),

("Risk & Insurance", "Insurance float",
 "Holding and using others' premiums during the gap before claims come due.",
 "Honeypot ant repletes",
 "Specialized 'replete' workers store food in their distended bodies, holding the colony's collective surplus that nestmates draw on later in lean times. Value is pooled and held in trust during the gap before it is needed.",
 80,
 "Colony honey stores",
 "A hive accumulates honey from many foragers and holds it as a communal reserve drawn down later through winter. The collected surplus is held and used across the lag before 'claims' (lean days) arrive.",
 76, ""),

("Risk & Insurance", "Precautionary reserves",
 "Holding idle surplus you hope never to use, sized to the worst plausible season.",
 "Hibernation fat storage",
 "Bears and marmots gorge in autumn to build fat reserves sized to survive a whole winter without eating. The buffer sits unused day to day but is built for the lean season ahead.",
 86,
 "Pika hay piles",
 "Pikas spend the short summer cutting and curing 'haystacks' of vegetation stored in their dens to feed on through alpine winter. A deliberately oversized reserve hedges against a long, harsh cold season.",
 82, ""),

# ===================== COMPOUNDING & GROWTH =====================
("Compounding & Growth", "The compounding acceleration phase",
 "The late stage where growth visibly feeds on prior growth and the curve bends upward.",
 "Exponential colony growth",
 "A young wasp nest or bacterial population grows slowly at first, but because each new member helps produce still more members, growth accelerates until the curve bends sharply upward. Output compounds because each addition enlarges the base that generates the next addition.",
 85,
 "Beaver pond snowball",
 "Each stick a beaver adds raises the water, which floods more land, eases transport of more building material, and supports more food, enabling still more building. Early gains create the conditions for faster later gains.",
 78, ""),

("Compounding & Growth", "Breaking the compounding chain",
 "How one early withdrawal resets the whole engine rather than just denting it.",
 "Interrupted hibernation arousal",
 "Rousing from hibernation burns a hugely disproportionate share of a hibernator's fat reserves; repeated disturbances can drain the whole winter budget and prove fatal. One interruption does not merely dent the reserve, it can collapse the entire survival plan.",
 80,
 "Repeatedly raided cache restart",
 "An animal whose store is plundered must begin accumulating again from zero, losing not just the food but all the compounding 'head start' the store represented.",
 74, ""),

("Compounding & Growth", "Reinvestment of yield",
 "Redirecting the harvest back into the principal instead of consuming it.",
 "Leafcutter ant fungus farming",
 "Leafcutter ants do not eat the leaves they cut; they feed them to a fungus garden and harvest the fungus's growth, continually feeding the cultivated asset rather than consuming the raw input. Yield is plowed back to grow a compounding living asset.",
 88,
 "Forgotten caches becoming nut trees",
 "Squirrels and jays bury far more seeds than they recover, and the forgotten ones grow into trees that produce future harvests. Stored 'capital' that is reinvested (planted) generates new productive assets.",
 78, ""),

("Compounding & Growth", "Doubling time (Rule of 72)",
 "A small steady rate quietly converting into a predictable doubling interval.",
 "Bacterial binary fission",
 "Bacteria divide on a fixed schedule, so a population doubles every set interval; a modest constant rate translates into relentless, predictable doublings. The clockwork of doubling time made literal.",
 85,
 "Lily-pond / algal doubling",
 "Surface algae that double their coverage each day fill the pond imperceptibly until the final few doublings cover it suddenly. A fixed rate produces a predictable doubling cadence and a deceptively late explosion.",
 78, ""),

("Compounding & Growth", "Negative compounding (drawdowns)",
 "Losses compounding downward, so recovery needs a bigger gain than the fall.",
 "Extinction vortex / Allee effect",
 "As a population shrinks, inbreeding, poorer mate-finding, and weaker group defense each lower reproduction further, accelerating the decline. Losses compound on losses, so climbing back requires far more than reversing the original drop.",
 82,
 "Trophic cascade collapse",
 "Removing a keystone species triggers knock-on losses through the food web that compound into a far larger systemic decline than the initial loss alone.",
 74, ""),

("Compounding & Growth", "Inflation erosion",
 "The slow, continuous, barely noticed shrinkage of stored value.",
 "Cache spoilage and pilfering",
 "A buried store quietly loses value every day as food rots, dries out, or is nibbled by pilferers. The hoard's real worth erodes continuously and invisibly even though the pile still looks intact.",
 82,
 "Ever-growing incisors offsetting wear",
 "A beaver's or rodent's incisors wear down constantly and must keep growing just to maintain function; standing still means falling behind. Continuous erosion that must be perpetually offset mirrors purchasing power leaking away.",
 72, ""),

("Compounding & Growth", "Hyperinflation",
 "Value collapse feeding on itself as everyone spends faster to outrun it.",
 "Algal bloom overshoot-and-crash",
 "An algal bloom explodes by consuming nutrients ever faster, then crashes catastrophically when the resource base is exhausted and oxygen collapses. Self-accelerating overconsumption ends in a near-total collapse of the system's value.",
 78,
 "Locust plague resource destruction",
 "A swarm consumes vegetation faster and faster as it grows, stripping the landscape until nothing supports it and the swarm collapses. Runaway consumption destroys the very base that gave it worth.",
 74, "Conceptual (collapse dynamics), not a value-of-money analog"),

("Compounding & Growth", "Real vs nominal return",
 "The true growth left only after the silent erosion is subtracted.",
 "Net-energy optimal foraging",
 "What matters to a forager is not calories gathered but calories gathered minus calories spent gathering them; a rich patch far away can yield negative net energy. Only the return after costs is real, exactly as only return after inflation is real.",
 85,
 "Hummingbird energy budget",
 "A hummingbird must net more nectar energy than its costly hovering flight burns; gross intake is meaningless until flight costs are subtracted. The 'real' gain is what survives the deduction.",
 80, ""),

("Compounding & Growth", "Time value of money",
 "A unit held now being worth more than the same unit promised later.",
 "Animal delay-of-gratification",
 "Corvids and apes will take a smaller reward now over a larger reward later unless the wait is short and the payoff clearly bigger, revealing an internal discount on future value. A reward in the hand is valued above the same reward delayed.",
 82,
 "Sure-nearby vs richer-distant choice",
 "Foragers often prefer a certain nearby food item over a larger but more distant or delayed one, because the closer payoff is effectively worth more now.",
 76, ""),

("Compounding & Growth", "Discounting future cash flows",
 "Distant rewards shrinking in present worth the further away they sit.",
 "Hyperbolic discounting (pigeons, rats)",
 "In choice experiments, animals devalue delayed rewards steeply and non-linearly, so a reward far in the future is worth only a fraction of its delivered size today. The discount curve on future value is directly observable.",
 84,
 "Cache-with-pilfer-risk discount",
 "Food cached for the future is implicitly discounted by the chance it will rot or be stolen before retrieval, so animals weigh a future cache below an equivalent immediate meal.",
 76, ""),

# ===================== DEBT, CREDIT & LEVERAGE =====================
("Debt, Credit & Leverage", "Leverage's symmetric amplification",
 "Borrowed resources magnifying the gain and the fall by the exact same factor.",
 "Spring-loaded strike (trap-jaw ant, mantis shrimp)",
 "These animals store muscular energy in a latch and release it to deliver strikes far more powerful than muscle alone could, but a misfire wastes that amplified energy and can injure the user. Stored, 'borrowed' force multiplies the outcome in both directions.",
 78,
 "Tool-use force multiplication",
 "A chimp using a rock to crack a nut multiplies its effective force, but a misjudged strike amplifies the cost (smashed food, hurt hand) just as much. The multiplier cuts both ways.",
 74, "Leverage is mechanical; treat as illustrative, not exact"),

("Debt, Credit & Leverage", "The debt spiral",
 "Interest compounding against you faster than you can possibly repay it.",
 "Starvation energy spiral",
 "A starving predator grows too weak to hunt successfully, which deepens its energy deficit, which weakens it further; the gap widens faster than any single meal can close it. The deficit compounds against the animal exactly like runaway interest.",
 85,
 "Quicksand / tar-pit struggle",
 "In quicksand or a tar seep, every struggling movement sinks the animal deeper, so effort to escape accelerates the descent. The position worsens faster than the animal can recover it.",
 78, ""),

("Debt, Credit & Leverage", "Collateral",
 "Pledging something you value to shrink the lender's risk and your rate.",
 "Nuptial gift as a bond",
 "Male hangingflies and dance flies present a captured prey item the female consumes during mating; the gift is a pledged asset that secures the partnership and reduces the female's 'risk' of a poor mate. Something of value is put up to seal the deal.",
 76,
 "Held nest/territory as security",
 "In many pair bonds, control of a quality nest site or territory functions as a stake that secures the partnership; losing it weakens the holder's standing in the relationship.",
 70, "Collateral has no clean animal analog; flagged as a stretch"),

("Debt, Credit & Leverage", "Creditworthiness as reputation",
 "Repeated reliable repayment slowly unlocking larger future access.",
 "Cleaner-fish image scoring",
 "Client fish watch how a cleaner treats other clients and preferentially approach cleaners with a track record of honest service while avoiding known cheats. A reputation for reliable 'repayment' (good service) unlocks more and better business.",
 90,
 "Primate reciprocity reputation",
 "Monkeys preferentially groom and form coalitions with partners who have reliably reciprocated before; a history of honoring exchanges grants greater access to future cooperation.",
 84, "Cleaner fish " + V),

("Debt, Credit & Leverage", "Default contagion",
 "One borrower's failure cascading through everyone financially connected to them.",
 "Tar-pit predator trap cascade",
 "A single mired herbivore attracts predators, which themselves become trapped, attracting scavengers that are trapped in turn. One failure draws in and brings down everyone connected to it, exactly as the La Brea fossil record shows.",
 82,
 "Mutualist-dependency cascade",
 "When a keystone partner (e.g., a fig or a pollinator) fails, every species dependent on it suffers in turn, propagating one collapse through a web of obligations.",
 78, ""),

("Debt, Credit & Leverage", "The margin call",
 "Being forced to liquidate the instant your posted collateral drops too far.",
 "Reserve-threshold forced abandonment",
 "When an animal's fat reserves fall below a critical line, it is forced to abandon territory, offspring, or a contest it can no longer afford, regardless of its wishes. Crossing the threshold triggers an involuntary liquidation of its position.",
 82,
 "Nest abandonment at starvation threshold",
 "An incubating parent whose reserves hit a critical low is forced to desert the eggs to save itself, liquidating the reproductive investment the moment its 'collateral' fails.",
 78, ""),

("Debt, Credit & Leverage", "Seniority in bankruptcy",
 "A strict pecking order deciding who eats first when the remaining assets are scarce.",
 "Carcass feeding succession",
 "At a kill, a strict order governs access: the apex predator feeds first, then mesopredators, then vultures, then insects, each taking what the seniors leave. When the resource is finite, priority is rigidly enforced.",
 88,
 "Dominance pecking order at food",
 "At a limited food source, dominant individuals feed first and subordinates take only the remainder, a literal pecking order that allocates a scarce pool by rank.",
 82, ""),

("Debt, Credit & Leverage", "Refinancing",
 "Swapping old expensive debt for cheaper new debt when conditions improve.",
 "Hermit crab shell upgrade",
 "A hermit crab continuously assesses its current shell and, when a better-fitting, less burdensome shell becomes available, abandons the old one for the improved terms. It swaps its 'housing obligation' for a better deal when the option appears.",
 82,
 "Den/territory relocation to a better site",
 "Animals abandon a costly or poor-quality den or territory when a superior, cheaper-to-hold site opens up, replacing old terms with better ones.",
 74, ""),

("Debt, Credit & Leverage", "Maturity mismatch",
 "Borrowing short-term to fund long-term commitments, fine until everyone wants out.",
 "Transient-bloom nesting commitment",
 "Some birds initiate long breeding commitments cued to a short-lived food bloom; if the bloom vanishes before chicks fledge, the long-term obligation outlives the short-term resource that funded it. A long commitment financed by a fleeting supply.",
 78,
 "Perishable cache vs long winter",
 "Storing short-shelf-life food to cover a long winter creates a mismatch: the obligation (survive the season) outlasts the maturity of the asset (food that spoils).",
 74, ""),

("Debt, Credit & Leverage", "Covenants",
 "Pre-agreed constraints the borrower accepts to reassure the lender.",
 "Mutualism sanctions (yucca moth, legume-rhizobia)",
 "Yuccas selectively abort flowers in which moths lay too many eggs, and legumes cut resources to rhizobia that fail to fix nitrogen. The host enforces pre-set terms by sanctioning partners that violate the agreement.",
 85,
 "Client punishment of cheating cleaners",
 "Client fish chase and refuse future service to cleaners that bite them, enforcing the implicit terms of honest cleaning through punishment.",
 80, "Cleaner-fish punishment " + V),

("Debt, Credit & Leverage", "Amortization",
 "Steadily chipping the principal down so the burden shrinks over time.",
 "Steady drawdown of a winter store",
 "An animal lives off a fixed cache through winter, drawing it down in regular increments so the remaining obligation (days to survive) and the store both shrink together toward zero. A fixed pool retired in steady portions.",
 78,
 "Incremental dam upkeep",
 "A beaver pays down the constant 'debt' of leaks and damage with steady incremental repairs, chipping away at the maintenance burden bit by bit.",
 70, "Amortization is a schedule, not a behavior; moderate fit"),

("Debt, Credit & Leverage", "Desperation pricing (usury)",
 "Charging the trapped and desperate the most, because they cannot walk away.",
 "Drought waterhole monopoly toll",
 "When a dominant animal controls the only water source in a drought, desperate drinkers must submit to harassment, displacement, or wait for scraps to access it. The monopolist extracts maximal concessions precisely because the desperate cannot go elsewhere.",
 80,
 "Monopoly-mutualist leverage",
 "An obligate partner that is the sole provider of an essential service (a lone pollinator species, for instance) holds outsized bargaining power over dependents who have no alternative.",
 74, ""),

# ===================== BANKING & MACRO =====================
("Banking & Macro", "The bank run",
 "A self-fulfilling panic where the fear that others will withdraw causes the withdrawal.",
 "Self-fulfilling stampede",
 "A herd stampedes not because each animal verified a threat but because the sight of others fleeing is itself the trigger to flee; the expectation that everyone runs makes everyone run. The panic is self-fulfilling, exactly like depositors rushing the bank because they expect others to.",
 86,
 "Alarm-pheromone mass evacuation",
 "An alarm pheromone causes each insect to flee and release more alarm signal, so the exodus feeds on itself and empties the nest faster than the original threat warranted.",
 78, ""),

("Banking & Macro", "Lender of last resort",
 "A backstop that calms panic mostly by existing, often without ever being used.",
 "Sentinel enabling calm",
 "A meerkat or pied babbler sentinel on watch lets the whole group forage calmly and efficiently; the mere reliable presence of the backstop, not its frequent intervention, is what prevents panic. Its value is in existing, like a credible lender of last resort.",
 84,
 "Protector's calming presence",
 "A dominant individual known to intervene in conflicts keeps the group orderly simply by being present; subordinates behave normally because the backstop is understood to be there if needed.",
 78, ""),

("Banking & Macro", "Fractional-reserve money creation",
 "The same deposited unit being lent out again and again, multiplying the supply.",
 "Trophallaxis chains",
 "A single nectar load is passed mouth to mouth through many ants or bees, nourishing numerous individuals as it circulates. One 'deposit' of food does work many times over as it moves through the colony, echoing how one deposit supports many loans.",
 80,
 "Shared-crop circulation",
 "Food held in the social crop is repeatedly regurgitated and shared, so the same resource underwrites multiple feedings across the colony rather than serving a single consumer once.",
 72, "Multiplier analogy is conceptual"),

("Banking & Macro", "Money velocity",
 "The same money changing hands faster, multiplying its real effect on the economy.",
 "Trophallaxis exchange rate",
 "The faster food is passed and redistributed among nestmates, the more individuals it nourishes per unit time; a colony with rapid sharing extracts more collective value from the same amount of food. Velocity of exchange amplifies real effect.",
 82,
 "Pollinator visitation rate",
 "The faster bees move pollen between flowers, the more fertilization the same pollen accomplishes per day. Higher turnover multiplies real output from a fixed stock.",
 76, ""),

("Banking & Macro", "Systemic / network risk",
 "A local failure propagating through interconnected nodes rather than staying contained.",
 "Pollination-network hub collapse",
 "In a plant-pollinator web, a few highly connected hub species hold the network together; losing one cascades failures to the many species that depended on it. Interconnection turns a local loss into a system-wide collapse.",
 85,
 "Mycorrhizal network disruption",
 "Forest trees are linked by shared fungal networks that move nutrients and signals; damaging key nodes disrupts resource flow across many connected trees at once.",
 78, ""),

("Banking & Macro", "Deposit insurance",
 "A guarantee that prevents the run precisely by making the run pointless.",
 "Crèche communal guarantee",
 "In eider duck and flamingo crèches, any nearby adult will defend any chick, so each parent is effectively guaranteed coverage and has no reason to panic-guard its own. The collective guarantee removes the incentive for a self-protective rush.",
 82,
 "Allonursing safety net",
 "In some communal mammals, females nurse one another's young, providing an implicit guarantee that a temporarily absent or failing mother's offspring are still covered, dampening individual panic.",
 76, ""),

("Banking & Macro", "Quantitative easing",
 "Flooding the system with liquidity to force activity when normal channels stall.",
 "Mast seeding (predator satiation)",
 "Oak and beech trees periodically flood the forest with far more seeds than seed-eaters can possibly consume, swamping the system so that enough seeds survive to sprout. Overwhelming the environment with supply forces the desired outcome through.",
 80,
 "Mass synchronized spawning",
 "Corals and fish release eggs and sperm in a single massive synchronized event, flooding the water so thoroughly that predators cannot consume it all and fertilization is assured. A deliberate glut to force a result.",
 76, "Conceptual link to liquidity flooding"),

("Banking & Macro", "Interest-rate transmission",
 "One central rate change rippling outward through every connected price.",
 "Alarm-call ripple",
 "A single sentinel's alarm call propagates through the group and onward to other species, instantly resetting everyone's behavior from foraging to vigilance. One central signal transmits through the whole network and changes all downstream activity.",
 82,
 "Pheromone broadcast shift",
 "A change in a colony's pheromone signal (e.g., queen or alarm pheromone) diffuses through the nest and shifts collective behavior across the board from one source.",
 78, ""),

("Banking & Macro", "The liquidity trap",
 "Easing stops working because fear keeps everyone hoarding no matter how cheap money gets.",
 "Landscape of fear suppressing foraging",
 "Even where food is abundant and easy to reach, the perceived presence of predators keeps prey hiding and under-foraging; lowering the 'cost' of feeding does not restart activity because fear dominates. Cheap opportunity goes unused.",
 85,
 "Persistent freeze despite safety",
 "An animal locked in a fear response stays frozen and inactive even after the threat passes and conditions are favorable, unable to resume normal economic activity.",
 76, ""),

("Banking & Macro", "Crowding out",
 "A large dominant borrower (the state) displacing smaller private borrowers from the pool.",
 "Competitive exclusion by a dominant",
 "A large dominant herbivore monopolizing a waterhole or grazing patch displaces smaller competitors who are pushed to poorer resources. The big claimant absorbs the shared pool and crowds the small out.",
 84,
 "Feeder monopolization",
 "An aggressive dominant bird that commandeers a feeder forces subordinates to wait or leave, soaking up the available resource at the expense of smaller users.",
 80, ""),

("Banking & Macro", "Seigniorage",
 "The profit captured simply from being the one allowed to issue the money.",
 "Queen's monopoly on reproductive issuance",
 "In a colony, the queen alone produces the eggs that constitute the colony's future 'value'; controlling the sole right of issuance confers her central power and the colony's investment flows to her. Profit and primacy come from monopolizing issuance.",
 74,
 "Bowerbird control of valued tokens",
 "A male who controls the supply of scarce valued decorations (or steals rivals') profits from owning the tokens others must compete for, extracting advantage from controlling the currency.",
 68, "Seigniorage is an abstract monetary concept; flagged stretch"),

("Banking & Macro", "Currency-peg defense",
 "Burning down a finite reserve to hold a price the market keeps pushing against.",
 "Territory boundary defense to exhaustion",
 "A territory holder spends finite energy repelling a stream of intruders to hold a fixed boundary; as reserves deplete against relentless pressure, the line eventually breaks. Defending a fixed level by burning a limited reserve mirrors a central bank defending a peg.",
 84,
 "Beaver dam against flood pressure",
 "A beaver expends continuous effort patching breaches to hold the water at a set level; when inflow overwhelms its repair capacity, the held level collapses.",
 78, ""),

("Banking & Macro", "The carry trade",
 "Borrowing where it's cheap to deploy where it yields more, vulnerable to a sudden snap.",
 "Central-place foraging risk",
 "An animal bases itself in a cheap, safe refuge and makes trips to richer but riskier distant patches to profit from the differential; the strategy pays until a predator catches it exposed mid-trip. Profitable spread-harvesting that is vulnerable to a sudden reversal.",
 78,
 "Cheap-base / rich-patch seasonal exploitation",
 "Wintering animals exploit a safe low-cost base while foraging a higher-yield risky area, earning the gap until a weather snap or predator turns the trade against them violently.",
 74, ""),

("Banking & Macro", "The deflationary spiral",
 "Falling prices freezing spending, which lowers prices further in a self-reinforcing loop.",
 "Allee effect",
 "Below a critical density, fewer individuals mean harder mate-finding and weaker group defense, which lowers reproduction and shrinks the population further. Decline reinforces decline in a self-feeding downward loop, the demographic mirror of a deflationary spiral.",
 85,
 "Collapsing huddle feedback",
 "As a warmth-sharing huddle loses members, it generates less heat, driving more individuals to leave or die, which cools it further. Each loss makes the next loss more likely.",
 78, ""),

# ===================== CORPORATE FINANCE & VALUATION =====================
("Corporate Finance & Valuation", "Opportunity cost",
 "The unseen cost of the path not taken whenever a finite resource is committed.",
 "Marginal value theorem (patch-leaving)",
 "A forager in a depleting patch must decide when to leave for a fresh one; staying past the optimum forfeits the richer returns available elsewhere. The cost of staying is the foregone better patch, the essence of opportunity cost.",
 88,
 "Mating-vs-foraging time allocation",
 "Time a male spends displaying for mates is time not spent feeding; every hour committed to one pursuit is an hour's worth of the other surrendered.",
 80, ""),

("Corporate Finance & Valuation", "The sunk-cost fallacy",
 "Continuing because of what's already spent rather than what's still ahead.",
 "Concorde fallacy in parental investment",
 "It has been argued that some animals defend or provision a current brood more fiercely the more they have already invested in it, rather than judging only its future prospects. Past investment, not future payoff, appears to drive continued commitment.",
 75,
 "Defending a failing territory",
 "An animal may persist in defending a degraded territory it has long held and invested in, beyond the point where moving on would pay better.",
 70, "Animal sunk-cost evidence is debated; flag before scripting"),

("Corporate Finance & Valuation", "Economies of scale",
 "Per-unit cost falling as size grows, rewarding the big over the small.",
 "Cooperative pack hunting",
 "Wolves, lions, and wild dogs hunting in larger groups can bring down big prey at a lower energy cost per individual than a lone hunter could ever manage. Per-capita cost falls and per-capita payoff rises with group size.",
 86,
 "Huddle surface-area economy",
 "A larger huddle or hive loses less heat per individual because volume grows faster than exposed surface, so each member pays less to stay warm. Scale lowers unit cost directly.",
 82, ""),

("Corporate Finance & Valuation", "Network effects",
 "Each new participant making the whole more valuable to every existing one.",
 "Ant trail reinforcement (stigmergy)",
 "Every ant that uses a pheromone trail strengthens it, making the route more attractive and useful to the next ant. The path's value to each user grows with the number of users, the defining feature of a network effect.",
 86,
 "Slime-mold network connectivity",
 "As a slime mold links more food nodes into its tubular network, the whole connected system becomes more valuable and efficient for moving resources, with each added link enhancing the rest.",
 78, "Slime mold " + V),

("Corporate Finance & Valuation", "The economic moat",
 "Defending captured territory or resources to keep rivals from eroding your returns.",
 "Scent-marked territory defense",
 "Animals mark and defend territory boundaries to exclude rivals from a resource, preserving privileged access and the returns it yields. A durable defended barrier protects the holder's stream of value, exactly like a competitive moat.",
 82,
 "Beaver lodge water moat",
 "A beaver's dam-created pond surrounds its lodge with water that keeps land predators out, a literal moat protecting the asset and the returns it shelters.",
 80, ""),

("Corporate Finance & Valuation", "Creative destruction",
 "Nimble newcomers displacing entrenched incumbents that stopped adapting.",
 "Fire-driven ecological succession",
 "A forest fire destroys the mature canopy that monopolized light, releasing serotinous pine seeds and letting fast pioneer species boom in the cleared space. Destruction of incumbents opens the field for vigorous new entrants.",
 82,
 "Alpha takeover turnover",
 "A challenger overthrows an aging dominant, resetting the group's order and reproduction; the old regime is displaced by a fitter newcomer in a cycle of renewal.",
 78, ""),

("Corporate Finance & Valuation", "Dividend vs reinvestment",
 "Choosing between harvesting now and feeding the engine to grow the harvest later.",
 "Reproduce-now vs grow-bigger tradeoff",
 "Organisms allocate energy between reproducing immediately and growing a larger body that yields bigger future broods (income vs capital breeding, semelparity vs iteroparity). Paying out now versus reinvesting for greater later output is the core dividend question.",
 85,
 "Consume-vs-cache a seed",
 "An animal can eat a seed now (a dividend) or cache/plant it for future return; the choice between immediate consumption and reinvestment is direct.",
 78, ""),

("Corporate Finance & Valuation", "Share buybacks",
 "Shrinking the total pool so each remaining slice represents more.",
 "Brood reduction / siblicide",
 "When resources are tight, parents allow or cause the loss of the weakest chicks (sometimes via siblicide) so that the survivors each receive a larger share of provisioning. Shrinking the number of claimants concentrates value in those that remain.",
 80,
 "Litter culling / runt elimination",
 "Some mammals lose or abandon the runt of a litter, concentrating maternal investment on fewer, stronger offspring whose individual share rises.",
 74, ""),

("Corporate Finance & Valuation", "Dilution",
 "New shares quietly shrinking the size of every existing holder's slice.",
 "Conspecific egg-dumping",
 "Some birds secretly lay eggs in a neighbor's nest (intraspecific brood parasitism), so the host unknowingly divides its care among more mouths, shrinking each legitimate chick's share. Extra 'shares' issued into the nest dilute every existing claim.",
 82,
 "Extra-mouths share reduction",
 "Any added dependent (a parasite chick, an extra hatchling) reduces the per-capita provisioning each original offspring receives, diluting their effective stake.",
 78, ""),

("Corporate Finance & Valuation", "Mark-to-market",
 "Constantly revaluing what you hold to whatever it would fetch right now.",
 "Cache re-inspection and resizing",
 "Acorn woodpeckers revisit stored acorns, check them for fit and freshness, and re-drill holes as acorns shrink, continually re-valuing the store to its current real condition rather than its original worth.",
 80,
 "Real-time rival assessment",
 "In contests, animals continuously reassess an opponent's current condition and fighting ability rather than relying on past reputation, updating their valuation to the present moment.",
 76, "Woodpecker re-inspection " + V),

("Corporate Finance & Valuation", "Goodwill",
 "Paying above tangible worth for something intangible you believe is really there.",
 "Mate-choice premium for display",
 "A peahen accepts a male whose enormous train carries no direct material benefit, paying a 'premium' for an intangible signal of underlying genetic quality she cannot directly measure. Value is assigned above any tangible asset.",
 76,
 "Reputation premium in partner choice",
 "Animals favor partners with intangible histories of reliability or status, effectively paying above the partner's measurable resources for that unquantifiable quality.",
 72, ""),

("Corporate Finance & Valuation", "Going-concern vs liquidation value",
 "A living, working whole being worth far more than the sum of its sold-off parts.",
 "Functioning colony vs scattered parts",
 "A working bee or ant colony coordinates foraging, defense, and brood care into something far more valuable than the same individuals dispersed; break it up and the value largely vanishes. The going concern vastly exceeds the liquidation value.",
 82,
 "Superorganism dependency",
 "In eusocial species, individuals removed from the colony usually cannot survive or reproduce alone, so the organized whole is worth far more alive and intact than its separable members.",
 78, ""),

("Corporate Finance & Valuation", "Costly signaling",
 "Spending real, hard-to-fake resources purely to prove a hidden quality is genuine.",
 "Stotting gazelle (handicap principle)",
 "A gazelle that spots a predator often leaps straight up on stiff legs, spending energy and time to broadcast 'I am so fit I can waste effort and still escape.' Because only genuinely fit animals can afford the costly display, the signal is honest and predators often break off.",
 92,
 "Peacock train",
 "The peacock's enormous, metabolically expensive, predator-attracting train is costly precisely because a low-quality male could not sustain it, making it an honest advertisement of genetic quality.",
 86, "Stotting " + V),

("Corporate Finance & Valuation", "The principal-agent problem",
 "A hired manager's incentives quietly drifting away from the owner's interests.",
 "Worker policing in colonies",
 "Worker bees and ants have a personal incentive to lay their own eggs, which conflicts with the colony's collective optimum, so other workers 'police' and destroy such eggs to realign behavior. The agents' private interests diverge from the principal's, requiring enforcement.",
 84,
 "Cleaner-fish agency conflict",
 "A cleaner's private incentive is to bite the client for nutritious mucus, conflicting with the client's interest in honest cleaning; the misalignment is managed only through monitoring and punishment.",
 78, "Cleaner-fish " + V),

# ===================== BEHAVIORAL & STRATEGY =====================
("Behavioral & Strategy", "Loss aversion",
 "Feeling an equivalent loss far more intensely than the matching gain.",
 "Asymmetric territorial defense",
 "Animals typically fight far harder to keep territory they already hold than to gain equivalent new ground, and the resident usually wins. Losing what one has triggers a stronger response than acquiring the same amount, the hallmark of loss aversion.",
 82,
 "Reference-dependent foraging",
 "Experiments show animals evaluate outcomes relative to an expected reference point and react more strongly to shortfalls than to equal-sized windfalls, weighting losses above gains.",
 80, ""),

("Behavioral & Strategy", "Dollar-cost averaging",
 "Steady accumulation regardless of conditions to neutralize the timing problem.",
 "Steady seasonal caching",
 "A squirrel caches a roughly steady stream of food throughout the season regardless of any single day's abundance, so it accumulates a store without needing to 'time' the best foraging days. Consistent buying smooths out variance.",
 80,
 "Staggered reproduction over time",
 "Iteroparous animals spread reproductive effort across many seasons rather than betting everything on one, averaging out good and bad years through steady, repeated investment.",
 76, ""),

("Behavioral & Strategy", "Liquidity-vs-yield tradeoff",
 "Giving up instant access in exchange for a higher return on what's locked away.",
 "Fat reserves vs agility",
 "Stored fat is a high-yield energy buffer, but carrying it reduces speed and escape ability, so animals balance how much 'illiquid' reserve to hold against the need to stay nimble. More stored yield means less instant maneuverability.",
 84,
 "Buried cache vs carried food",
 "A buried cache offers a large secured return but cannot be accessed instantly, while food carried on the body is immediately available but limited and exposed. Access is traded against yield.",
 80, ""),

("Behavioral & Strategy", "Anchoring",
 "Fixating on an irrelevant first reference and judging everything against it.",
 "Filial imprinting",
 "A newly hatched gosling fixes on the first moving object it sees and treats it as 'mother' thereafter, anchoring all subsequent behavior to that initial, possibly arbitrary, reference. The first impression sets the standard.",
 80,
 "Search-image fixation",
 "A predator that has found one prey type forms a 'search image' and keeps hunting that type, anchored to its recent reference even as other prey go overlooked.",
 74, ""),

("Behavioral & Strategy", "Social proof in adoption",
 "Trusting that if many others chose it, it must be safe to choose too.",
 "Mate-choice copying",
 "Female guppies, sage grouse, and fruit flies are more likely to choose a male they have seen other females choose, taking others' choices as proof of quality. Popularity itself becomes the reason to adopt.",
 86,
 "Conformist foraging transmission",
 "Great tits and other animals adopt the food type or technique used by the majority around them, sometimes even against their own prior experience, conforming to the popular option.",
 82, ""),

("Behavioral & Strategy", "Recency bias",
 "Over-weighting the most recent events as if they'll simply continue forever.",
 "Recent-outcome foraging weighting",
 "Foragers disproportionately weight the outcome of their most recent visits when deciding where to feed next, chasing wherever luck just struck and abandoning sites after a recent miss. The latest result dominates the estimate.",
 80,
 "Post-scare vigilance spike",
 "Vigilance shoots up right after a predator scare and gradually fades, so behavior is driven by how recent the last threat was rather than the long-run risk.",
 74, ""),

("Behavioral & Strategy", "The disposition effect",
 "Selling winners too early while clinging to losers far too long.",
 "Patch over-staying",
 "Foragers often abandon rich patches sooner than optimal yet linger too long in depleting ones, reluctant to 'realize' the poor patch as a loss. Quitting winners early and clinging to losers mirrors the disposition effect.",
 78,
 "Failing-territory retention",
 "An animal may hold onto a declining territory long past the point of profitability, unwilling to give up on a losing position it has committed to.",
 74, ""),

("Behavioral & Strategy", "FOMO-driven entry",
 "Buying late and high purely from the fear of being left behind.",
 "Feeding-frenzy local enhancement",
 "Gulls and sharks rush to join a feeding frenzy simply because others are feeding there, often arriving late as the resource is already depleting. The sight of others profiting pulls in latecomers regardless of remaining value.",
 84,
 "Carcass pile-on",
 "Vultures descending on a carcass draw still more vultures from miles around, many arriving after the best portions are gone, piling in for fear of missing the bonanza.",
 80, ""),

("Behavioral & Strategy", "Time preference",
 "Choosing a smaller reward now over a larger reward that requires waiting.",
 "Delay-of-gratification tests",
 "Corvids, parrots, and apes can sometimes forgo an immediate treat to wait for a larger one, but readily reveal a preference for sooner-smaller when the wait grows. Their choices directly expose the rate at which they discount the future.",
 85,
 "Caching as deferred consumption",
 "Choosing to cache food rather than eat it now is a literal choice of a larger future payoff over immediate consumption, the behavioral expression of low time preference.",
 80, ""),

("Behavioral & Strategy", "Mental accounting",
 "Treating identical money differently depending on which mental 'jar' it sits in.",
 "Nutrient-specific appetites",
 "Animals maintain separate regulatory 'budgets' for protein, fat, salt, and water, seeking each independently rather than treating all calories as fungible. Resources are bucketed into distinct accounts rather than pooled.",
 76,
 "Cache vs consume mental split",
 "Food earmarked for caching is often handled differently from food destined for immediate eating, as if it sits in a separate account with its own rules.",
 72, ""),

# ===================== DERIVATIVES & ADVANCED =====================
("Derivatives & Advanced", "Arbitrage",
 "Exploiting the same thing being priced differently in two places at once.",
 "Resource-gradient exploitation (traplining)",
 "Traplining pollinators and primates learn predictable differences in reward across known sites and route themselves to harvest the gaps, profiting from a value mismatch between locations. Exploiting a price difference across patches is a foraging arbitrage.",
 76,
 "Niche arbitrage by innovators",
 "Innovative animals (e.g., crows exploiting an untapped food source others ignore) profit from a mispriced opportunity until competitors move in and close the gap.",
 72, "Arbitrage is riskless by definition; animal versions carry risk"),

("Derivatives & Advanced", "Convexity / optionality",
 "A payoff with a capped downside but an open-ended upside.",
 "Exploratory innovation",
 "Curious animals try cheap, low-risk experiments (novel foods, new tools, odd routes); most attempts cost little and fail, but the occasional success unlocks a large new payoff. Limited downside, open-ended upside is exactly optionality.",
 84,
 "r-strategy lottery",
 "An r-strategist produces vast numbers of cheap offspring, each with a tiny chance of survival; the per-offspring cost is small and bounded while a rare winner can found a whole new population.",
 80, ""),

("Derivatives & Advanced", "Theta (time) decay",
 "An option steadily bleeding value with each day that passes, all else equal.",
 "Perishable cache decay",
 "A stored carcass or cache loses value every day it goes unused as it rots, dries, or is found; the 'option' to consume it bleeds worth purely with the passage of time. Holding it costs value each day.",
 84,
 "Closing mating window",
 "A receptive female's fertile window shrinks daily; a male's option to mate decays in value as time runs out regardless of anything else, like an option approaching expiry.",
 80, ""),

("Derivatives & Advanced", "The gamma squeeze",
 "Hedging flows being forced to chase the underlying, accelerating its own move.",
 "Snowballing mob recruitment",
 "Mobbing birds attract ever more mobbers as the commotion grows, and the swelling response forces the target to move, which intensifies the mob further. A self-reinforcing forced response accelerates the very movement it reacts to.",
 72,
 "Alarm-pheromone escalation",
 "An alarm pheromone provokes responses that release more pheromone, forcing an escalating collective reaction that feeds on itself.",
 68, "Gamma squeeze is highly mechanism-specific; flagged as a stretch"),

("Derivatives & Advanced", "Volatility clustering",
 "Turbulent periods bunching together, calm following calm and storm following storm.",
 "Predator-presence panic clustering",
 "When a predator is in the area, a prey group experiences repeated flushes and panics in quick succession, then long stretches of calm once it leaves. Turbulent episodes cluster in time rather than spreading evenly, exactly like volatility.",
 82,
 "Boom-bust activity bouts",
 "Many animals show bursts of intense activity (feeding frenzies, breeding swarms) bunched together, separated by quiet periods, producing clustered rather than uniform turbulence.",
 76, ""),

("Derivatives & Advanced", "Contango / backwardation",
 "The future price sitting above or below today's, revealing scarcity or glut.",
 "Seasonal stored-value premium",
 "Food that is abundant and cheap in autumn becomes precious in winter, so its 'future price' rises far above its present glut value, driving the intensity of hoarding. The spread between now and later reflects expected scarcity.",
 80,
 "Anticipatory hoarding signal",
 "How hard animals hoard ahead of a hard season implicitly prices future scarcity; heavy pre-winter caching reveals a high expected future value relative to the present.",
 74, ""),

("Derivatives & Advanced", "Counterparty risk",
 "The other side of your deal failing to pay when it finally matters.",
 "Mutualist cheating (cleaner bites client)",
 "A cleaner fish can renege on the deal by biting the client for mucus instead of removing parasites; the partner defaults on the agreed exchange. Relying on a counterparty that may cheat is counterparty risk made literal.",
 86,
 "Hunting-partner defection",
 "In cooperative hunts, a partner that fails to commit at the critical moment leaves the others exposed and empty-handed, defaulting on the implicit deal when it counts most.",
 80, "Cleaner-fish cheating " + V),

("Derivatives & Advanced", "Netting",
 "Offsetting mutual obligations so only the small net difference must actually change hands.",
 "Reciprocal-exchange offsetting",
 "In biological markets, partners that both give and receive favors (food, grooming, support) effectively offset mutual obligations over time, so only the net imbalance shapes the relationship rather than every transaction settling separately.",
 78,
 "Grooming-debt netting",
 "Reciprocal allogrooming partners trade bouts back and forth, so the running give-and-take cancels out and only the net grooming 'owed' matters to the bond.",
 72, ""),

("Derivatives & Advanced", "Tranching",
 "Slicing one pool of risk into stacked layers that absorb losses in strict order.",
 "Selfish-herd center vs edge",
 "In a herd, peripheral individuals absorb predation first while those in the protected center are hit only if the outer layer is breached. Risk is stratified into layers that take losses in a strict order, exactly like junior and senior tranches.",
 82,
 "Sacrificial caste first-loss",
 "Soldier ants and termites, or musk-ox bulls forming an outer defensive ring around calves, absorb the first and heaviest losses so the protected core survives. A designated layer takes the first hit.",
 78, ""),

("Derivatives & Advanced", "Portfolio rebalancing",
 "Periodically trimming what grew and topping up what shrank to restore target weights.",
 "Patch-switching effort reallocation",
 "Foragers continually shift effort away from patches they have depleted (the overweight winners) toward fresher, richer ones (the underweight laggards) to keep their overall intake balanced. Reallocating toward the underweighted is rebalancing.",
 84,
 "Ideal free distribution",
 "Animals distribute themselves across patches in proportion to each patch's resources, and self-correct when one becomes crowded or depleted, continually restoring a balanced allocation across the 'portfolio' of sites.",
 84, ""),
]

assert len(DATA) == 100, f"Expected 100 rows, got {len(DATA)}"

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Concept-Animal Matches"

headers = [
    "#", "Category", "Granular Concept", "The Specific Finance Aspect",
    "Animal Match 1", "Match 1 - Behavior Description (script-ready)", "Match 1 Quality %",
    "Animal Match 2", "Match 2 - Behavior Description (script-ready)", "Match 2 Quality %",
    "Notes / Verification",
]

header_fill = PatternFill("solid", fgColor="1F4E5F")
header_font = Font(bold=True, color="FFFFFF", size=11)
cat_fill = PatternFill("solid", fgColor="EAF1F3")
m1_fill = PatternFill("solid", fgColor="F3F8E8")
m2_fill = PatternFill("solid", fgColor="FBF1E8")
thin = Side(style="thin", color="D0D0D0")
border = Border(left=thin, right=thin, top=thin, bottom=thin)
wrap = Alignment(vertical="top", wrap_text=True)
center = Alignment(vertical="top", horizontal="center", wrap_text=True)


def q_fill(q):
    if q >= 85:
        return PatternFill("solid", fgColor="C6EFCE")  # green
    if q >= 75:
        return PatternFill("solid", fgColor="FFEB9C")  # amber
    return PatternFill("solid", fgColor="FFC7CE")        # red


ws.append(headers)
for col in range(1, len(headers) + 1):
    c = ws.cell(row=1, column=col)
    c.fill = header_fill
    c.font = header_font
    c.alignment = Alignment(vertical="center", horizontal="center", wrap_text=True)
    c.border = border

for i, row in enumerate(DATA, start=1):
    cat, concept, aspect, a1, d1, q1, a2, d2, q2, notes = row
    ws.append([i, cat, concept, aspect, a1, d1, q1, a2, d2, q2, notes])
    r = i + 1
    for col in range(1, len(headers) + 1):
        cell = ws.cell(row=r, column=col)
        cell.border = border
        cell.alignment = center if col in (1, 7, 10) else wrap
    ws.cell(row=r, column=2).fill = cat_fill
    ws.cell(row=r, column=3).font = Font(bold=True)
    ws.cell(row=r, column=5).fill = m1_fill
    ws.cell(row=r, column=5).font = Font(bold=True)
    ws.cell(row=r, column=6).fill = m1_fill
    ws.cell(row=r, column=7).fill = q_fill(q1)
    ws.cell(row=r, column=7).font = Font(bold=True)
    ws.cell(row=r, column=8).fill = m2_fill
    ws.cell(row=r, column=8).font = Font(bold=True)
    ws.cell(row=r, column=9).fill = m2_fill
    ws.cell(row=r, column=10).fill = q_fill(q2)
    ws.cell(row=r, column=10).font = Font(bold=True)

widths = {"A": 4, "B": 22, "C": 28, "D": 40, "E": 26, "F": 62,
          "G": 9, "H": 26, "I": 62, "J": 9, "K": 30}
for col, w in widths.items():
    ws.column_dimensions[col].width = w

ws.freeze_panes = "C2"
ws.auto_filter.ref = f"A1:K{len(DATA) + 1}"

# ---- second sheet: a quick legend ----
ws2 = wb.create_sheet("Legend")
legend = [
    ["How to read this workbook", ""],
    ["", ""],
    ["Quality %", "How cleanly the animal behavior maps to the SPECIFIC finance aspect (and how biologically accurate it is)."],
    ["  85-100 (green)", "Strong, launch-ready pairing. The mechanism genuinely matches."],
    ["  75-84 (amber)", "Good pairing with a small stretch; usable with care in the script."],
    ["  Below 75 (red)", "Conceptual or loose fit. Use only if you lean into 'where the analogy breaks down.'"],
    ["", ""],
    ["Notes / Verification", "'Web-verified' = the core biological claim was checked against scientific sources (Nature, Science, PNAS, university research) during research."],
    ["Script-ready description", "Each description states the real biology AND the parallel, so it can be handed straight to a model to expand into a full episode script."],
    ["", ""],
    ["Suggested first episodes (highest-confidence pairings)", ""],
    ["  Risk pooling", "Vampire bat reciprocal blood sharing (96%)"],
    ["  Costly signaling", "Stotting gazelle / peacock train (92%)"],
    ["  Momentum as self-fuel", "Desert locust phase change (92%)"],
    ["  Price discovery", "Honeybee swarm quorum (94%)"],
    ["  Creditworthiness as reputation", "Cleaner-fish image scoring (90%)"],
    ["  Diversification", "Scatter-hoarding across caches (90%)"],
    ["  Hedging", "Bet-hedging via staggered germination (90%)"],
]
for row in legend:
    ws2.append(row)
ws2.column_dimensions["A"].width = 48
ws2.column_dimensions["B"].width = 70
ws2["A1"].font = Font(bold=True, size=13)
for r in range(1, len(legend) + 1):
    ws2.cell(row=r, column=2).alignment = wrap

out = "/home/user/dataexploration/finance_animal_behavior_matches.xlsx"
wb.save(out)
print("Saved:", out)
print("Rows:", len(DATA), "| Matches:", len(DATA) * 2)

# distribution of quality scores
allq = [r[5] for r in DATA] + [r[8] for r in DATA]
print("Quality: green(>=85):", sum(q >= 85 for q in allq),
      "| amber(75-84):", sum(75 <= q < 85 for q in allq),
      "| red(<75):", sum(q < 75 for q in allq))
